### ISSUE TITLE
Accept arbitrary dates for stats-export tool

### ISSUE THREAD

**Issue by jkarner** [letsencrypt/sre-tools#6]
The stats-export tool creates a time period for the query that is today()-24h. In cases where the tool exits or is unable to be run, it should accept an arbitrary date to use for the start date and calculate the 24 hour window for stats collection.

**Comment by pgporada** [comment]
This is spurred by missing stats from June 25th and 26th. 
![le-stats](https://user-images.githubusercontent.com/2382565/60825450-b9184100-a179-11e9-917d-a295c265e985.png)
